---
# tasks file for lvm

- name: Create partition 
  parted: 
    device: "{{ disk  }}" 
    number: 1 
    flags: [ lvm ]
    state: present 
    part_end: "{{ part_size }}" 

- name: Create volume group 
  lvg: 
    vg:    "{{ vg_name }}"
    pvs:   "{{ pv      }}"
    pesize: 4  
- name: Create logical volume 
  lvol:
    vg: "{{ vg_name }}"  
    lv: "{{ lv_name }}"
    size: "{{ lv_size }}"
    force: yes 
- name: Format the LVM with XFS file system 
  filesystem: 
    fstype: xfs 
    dev:   /dev/{{ vg_name }}/{{ lv_name }} 
- name: create the mount point 
  file: 
    path: "{{ mount_point }}"  
    state: directory 
    mode:  0755
- name: mount the LV on /ansible_lvm 
  mount: 
    path: "{{ mount_point }}"
    src: /dev/{{ vg_name }}/{{ lv_name }} 
    fstype: xfs 
    state: mounted 
  when: mounted 


